/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import DAO.implement.NhanSu;
import Model.BacLuongModel;
import Model.ChucVuModel;
import Model.ComboItem;
import Model.NhanSuModel;
import Model.PhongBanModel;
import java.awt.Image;
import java.time.Duration;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;

/**
 *
 * @author Iroha
 */
public class detailInforNotEdit extends javax.swing.JDialog {

    hosoPanel previousPanel;
    NhanSuModel acc;
    ButtonGroup btn_gioitinh = new ButtonGroup();
    List<BacLuongModel> bl = new DAO.implement.BacLuong().getBacLuong();
    List<ChucVuModel> cv = new DAO.implement.ChucVu().getChucVu();
    List<PhongBanModel> pb = new DAO.implement.PhongBan().getPhongBan();
    String filename;
    boolean imageChange = false;
    
    /**
     * Creates new form detailInfor
     */
    public detailInforNotEdit(String MaNS, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btn_gioitinh.add(gioitinh_nam);
        btn_gioitinh.add(gioitinh_nu);
        acc = new NhanSu().getNhanSu(MaNS);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        jPanel1.setBackground(new java.awt.Color(255, 255, 255, 0));
        this.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_chinhtri.setLineWrap(true);
        txt_doanthe.setLineWrap(true);
        prepare();
    }
    
    public void prepare(){
       try {
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date date = formatter.parse(acc.getNgaySinh());Date dateToday = new Date();
            LocalDate d1 = LocalDate.parse(acc.getNgayThamGia(), DateTimeFormatter.ISO_LOCAL_DATE);
            LocalDate d2 = LocalDate.parse((String)formatter.format(dateToday), DateTimeFormatter.ISO_LOCAL_DATE);
            Duration diff = Duration.between(d1.atStartOfDay(), d2.atStartOfDay());
            long diffDays = diff.toDays();
            txt_namcongtac.setText(String.valueOf(diffDays/365) + " năm (" + acc.getNgayThamGia() +")");
        } catch (ParseException ex) {
            Logger.getLogger(detailInforNotEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
        //add thong tin.
        txt_mans.setText(acc.getMaNS());
        txt_chinhtri.setText(acc.getChinhTri());
        txt_doanthe.setText(acc.getDoanThe());
        txt_chuyennganh.setText(acc.getChuyenNganh());
        txt_dantoc.setText(acc.getDanToc());
        txt_hoten.setText(acc.getHoTen());
        txt_quequan.setText(acc.getQueQuan());
        txt_sdt.setText(acc.getSoDienThoai());
        txt_trinhdo.setText(acc.getTrinhDoHocVan());
        if(acc.isGioiTinh())
            gioitinh_nam.setSelected(true);
        else
            gioitinh_nu.setSelected(true);
        for(PhongBanModel s:pb)
        {
            if(s.getMaPB().equals(acc.getMaPB()))
                txt_phongban.setText(s.getTenPB());
        }
        for(ChucVuModel s:cv)
        {
            if(s.getMaCV().equals(acc.getMaCV()))
                txt_chucvu.setText(s.getTenCV());
        }
        txt_bacluong.setText(String.valueOf(acc.getBacLuong()));
        try{
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(acc.getAnh()).getImage().getScaledInstance(lb_avt.getWidth(), lb_avt.getHeight(), Image.SCALE_SMOOTH));
            lb_avt.setIcon(imageIcon);
        }
        catch(Exception e){
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator12 = new javax.swing.JSeparator();
        txt_bacluong = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txt_ngaysinh = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txt_phongban = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        txt_chucvu = new javax.swing.JTextField();
        btn_cancel = new javax.swing.JButton();
        lb_avt = new javax.swing.JLabel();
        txt_chuyennganh = new javax.swing.JTextField();
        txt_mans = new javax.swing.JTextField();
        txt_dantoc = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        txt_trinhdo = new javax.swing.JTextField();
        txt_quequan = new javax.swing.JTextField();
        txt_namcongtac = new javax.swing.JTextField();
        txt_hoten = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        gioitinh_nu = new javax.swing.JRadioButton();
        gioitinh_nam = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_chinhtri = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_doanthe = new javax.swing.JTextArea();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 190, -1));

        txt_bacluong.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_bacluong.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_bacluong.setForeground(new java.awt.Color(255, 255, 255));
        txt_bacluong.setBorder(null);
        txt_bacluong.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_bacluong.setEnabled(false);
        txt_bacluong.setOpaque(false);
        jPanel1.add(txt_bacluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 190, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 180, -1));

        txt_ngaysinh.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_ngaysinh.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_ngaysinh.setForeground(new java.awt.Color(255, 255, 255));
        txt_ngaysinh.setBorder(null);
        txt_ngaysinh.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_ngaysinh.setEnabled(false);
        txt_ngaysinh.setOpaque(false);
        jPanel1.add(txt_ngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 180, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 180, -1));

        txt_phongban.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_phongban.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_phongban.setForeground(new java.awt.Color(255, 255, 255));
        txt_phongban.setBorder(null);
        txt_phongban.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_phongban.setEnabled(false);
        txt_phongban.setOpaque(false);
        jPanel1.add(txt_phongban, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 180, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 200, -1));

        txt_chucvu.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_chucvu.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_chucvu.setForeground(new java.awt.Color(255, 255, 255));
        txt_chucvu.setBorder(null);
        txt_chucvu.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_chucvu.setEnabled(false);
        txt_chucvu.setOpaque(false);
        jPanel1.add(txt_chucvu, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 200, -1));

        btn_cancel.setBackground(new java.awt.Color(24, 98, 151));
        btn_cancel.setFont(new java.awt.Font("UVN Van", 0, 18)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("OK");
        btn_cancel.setBorder(null);
        btn_cancel.setBorderPainted(false);
        btn_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 170, 50));

        lb_avt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lb_avt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 180, 240));

        txt_chuyennganh.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_chuyennganh.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_chuyennganh.setForeground(new java.awt.Color(255, 255, 255));
        txt_chuyennganh.setBorder(null);
        txt_chuyennganh.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_chuyennganh.setEnabled(false);
        txt_chuyennganh.setOpaque(false);
        jPanel1.add(txt_chuyennganh, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 170, -1));

        txt_mans.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_mans.setFont(new java.awt.Font("UVN Van", 0, 14)); // NOI18N
        txt_mans.setForeground(new java.awt.Color(255, 255, 255));
        txt_mans.setBorder(null);
        txt_mans.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_mans.setEnabled(false);
        txt_mans.setOpaque(false);
        jPanel1.add(txt_mans, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 180, -1));

        txt_dantoc.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_dantoc.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_dantoc.setForeground(new java.awt.Color(255, 255, 255));
        txt_dantoc.setBorder(null);
        txt_dantoc.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_dantoc.setEnabled(false);
        txt_dantoc.setOpaque(false);
        jPanel1.add(txt_dantoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 200, -1));

        txt_sdt.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_sdt.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_sdt.setForeground(new java.awt.Color(255, 255, 255));
        txt_sdt.setBorder(null);
        txt_sdt.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_sdt.setEnabled(false);
        txt_sdt.setOpaque(false);
        jPanel1.add(txt_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 170, -1));

        txt_trinhdo.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_trinhdo.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_trinhdo.setForeground(new java.awt.Color(255, 255, 255));
        txt_trinhdo.setBorder(null);
        txt_trinhdo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_trinhdo.setEnabled(false);
        txt_trinhdo.setOpaque(false);
        jPanel1.add(txt_trinhdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 200, -1));

        txt_quequan.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_quequan.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_quequan.setForeground(new java.awt.Color(255, 255, 255));
        txt_quequan.setBorder(null);
        txt_quequan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_quequan.setEnabled(false);
        txt_quequan.setOpaque(false);
        jPanel1.add(txt_quequan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 180, -1));

        txt_namcongtac.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_namcongtac.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_namcongtac.setForeground(new java.awt.Color(255, 255, 255));
        txt_namcongtac.setBorder(null);
        txt_namcongtac.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_namcongtac.setEnabled(false);
        txt_namcongtac.setOpaque(false);
        jPanel1.add(txt_namcongtac, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 150, -1));

        txt_hoten.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_hoten.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_hoten.setForeground(new java.awt.Color(255, 255, 255));
        txt_hoten.setBorder(null);
        txt_hoten.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_hoten.setEnabled(false);
        txt_hoten.setOpaque(false);
        jPanel1.add(txt_hoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 200, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 200, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 180, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 200, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 170, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 200, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 170, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, 150, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 170, -1));

        gioitinh_nu.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        gioitinh_nu.setForeground(new java.awt.Color(255, 255, 255));
        gioitinh_nu.setText("Nữ");
        gioitinh_nu.setOpaque(false);
        jPanel1.add(gioitinh_nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        gioitinh_nam.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        gioitinh_nam.setForeground(new java.awt.Color(255, 255, 255));
        gioitinh_nam.setText("Nam");
        gioitinh_nam.setOpaque(false);
        jPanel1.add(gioitinh_nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        jLabel15.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ngày Sinh:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("UVN Van", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("HỒ SƠ NHÂN SỰ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 230, 40));

        jLabel1.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Họ tên:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quê quán:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Giới tính:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dân tộc:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Số điện thoại:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Trình độ:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Chuyên ngành:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phòng ban:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Đoàn thể:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mã nhân sự:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Chức vụ:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Bậc lương:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, -1, -1));

        jLabel13.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Thời gian công tác:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, -1));

        jLabel14.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Chính trị:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        txt_chinhtri.setEditable(false);
        txt_chinhtri.setColumns(20);
        txt_chinhtri.setRows(5);
        txt_chinhtri.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txt_chinhtri);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 200, 120));

        txt_doanthe.setEditable(false);
        txt_doanthe.setColumns(20);
        txt_doanthe.setRows(5);
        txt_doanthe.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txt_doanthe);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 200, 150));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/detailInfor.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 820, 500));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detailInforNotEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detailInforNotEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detailInforNotEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detailInforNotEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                detailInforNotEdit dialog = new detailInforNotEdit(null, new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JRadioButton gioitinh_nam;
    private javax.swing.JRadioButton gioitinh_nu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lb_avt;
    private javax.swing.JTextField txt_bacluong;
    private javax.swing.JTextArea txt_chinhtri;
    private javax.swing.JTextField txt_chucvu;
    private javax.swing.JTextField txt_chuyennganh;
    private javax.swing.JTextField txt_dantoc;
    private javax.swing.JTextArea txt_doanthe;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_mans;
    private javax.swing.JTextField txt_namcongtac;
    private javax.swing.JTextField txt_ngaysinh;
    private javax.swing.JTextField txt_phongban;
    private javax.swing.JTextField txt_quequan;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_trinhdo;
    // End of variables declaration//GEN-END:variables
}
