/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Logger;
import DAO.implement.NhanSu;
import Model.BacLuongModel;
import Model.ChucVuModel;
import Model.ComboItem;
import Model.PhongBanModel;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Iroha
 */
public class detailInforAdd extends javax.swing.JDialog {

    hosoPanel previousPanel;
    ButtonGroup btn_gioitinh = new ButtonGroup();
    List<BacLuongModel> bl = new DAO.implement.BacLuong().getBacLuong();
    List<ChucVuModel> cv = new DAO.implement.ChucVu().getChucVu();
    List<PhongBanModel> pb = new DAO.implement.PhongBan().getPhongBan();
    String filename;
    boolean imageChange = false;
    
    /**
     * Creates new form detailInfor
     */
    public detailInforAdd(hosoPanel pF, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btn_gioitinh.add(gioitinh_nam);
        btn_gioitinh.add(gioitinh_nu);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        jPanel1.setBackground(new java.awt.Color(255, 255, 255, 0));
        this.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_chinhtri.setLineWrap(true);
        txt_doanthe.setLineWrap(true);
        previousPanel = pF;
        prepare();
    }
    
    public void prepare(){
        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        for(PhongBanModel s:pb)
        {
            txt_phongban.addItem(new ComboItem(s.getTenPB(),s.getMaPB()));
        }
        for(ChucVuModel s:cv)
            txt_chucvu.addItem(new ComboItem(s.getTenCV(),s.getMaCV()));
        for(BacLuongModel s:bl)
            txt_bacluong.addItem(s.getBacLuong());
        gioitinh_nam.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_save1 = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        lb_avt = new javax.swing.JLabel();
        txt_chuyennganh = new javax.swing.JTextField();
        txt_mans = new javax.swing.JTextField();
        txt_dantoc = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        txt_trinhdo = new javax.swing.JTextField();
        txt_quequan = new javax.swing.JTextField();
        txt_hoten = new javax.swing.JTextField();
        txt_phongban = new javax.swing.JComboBox<>();
        txt_chucvu = new javax.swing.JComboBox<>();
        txt_bacluong = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        gioitinh_nu = new javax.swing.JRadioButton();
        gioitinh_nam = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_chinhtri = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_doanthe = new javax.swing.JTextArea();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_save1.setBackground(new java.awt.Color(24, 98, 151));
        btn_save1.setFont(new java.awt.Font("UVN Van", 0, 12)); // NOI18N
        btn_save1.setForeground(new java.awt.Color(255, 255, 255));
        btn_save1.setText("Thay Avatar");
        btn_save1.setBorder(null);
        btn_save1.setBorderPainted(false);
        btn_save1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 120, 30));

        btn_add.setBackground(new java.awt.Color(24, 98, 151));
        btn_add.setFont(new java.awt.Font("UVN Van", 0, 18)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("Thêm");
        btn_add.setBorder(null);
        btn_add.setBorderPainted(false);
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 110, 50));

        btn_cancel.setBackground(new java.awt.Color(24, 98, 151));
        btn_cancel.setFont(new java.awt.Font("UVN Van", 0, 18)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("Huỷ");
        btn_cancel.setBorder(null);
        btn_cancel.setBorderPainted(false);
        btn_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 110, 50));

        lb_avt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lb_avt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 180, 240));

        txt_chuyennganh.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_chuyennganh.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_chuyennganh.setForeground(new java.awt.Color(255, 255, 255));
        txt_chuyennganh.setBorder(null);
        txt_chuyennganh.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_chuyennganh.setOpaque(false);
        jPanel1.add(txt_chuyennganh, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 170, -1));

        txt_mans.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_mans.setFont(new java.awt.Font("UVN Van", 0, 14)); // NOI18N
        txt_mans.setForeground(new java.awt.Color(255, 255, 255));
        txt_mans.setBorder(null);
        txt_mans.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_mans.setOpaque(false);
        jPanel1.add(txt_mans, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 180, -1));

        txt_dantoc.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_dantoc.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_dantoc.setForeground(new java.awt.Color(255, 255, 255));
        txt_dantoc.setBorder(null);
        txt_dantoc.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_dantoc.setOpaque(false);
        jPanel1.add(txt_dantoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 200, -1));

        txt_sdt.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_sdt.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_sdt.setForeground(new java.awt.Color(255, 255, 255));
        txt_sdt.setBorder(null);
        txt_sdt.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_sdt.setOpaque(false);
        jPanel1.add(txt_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 170, -1));

        txt_trinhdo.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_trinhdo.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_trinhdo.setForeground(new java.awt.Color(255, 255, 255));
        txt_trinhdo.setBorder(null);
        txt_trinhdo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_trinhdo.setOpaque(false);
        jPanel1.add(txt_trinhdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 200, -1));

        txt_quequan.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_quequan.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_quequan.setForeground(new java.awt.Color(255, 255, 255));
        txt_quequan.setBorder(null);
        txt_quequan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_quequan.setOpaque(false);
        jPanel1.add(txt_quequan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 180, -1));

        txt_hoten.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_hoten.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_hoten.setForeground(new java.awt.Color(255, 255, 255));
        txt_hoten.setBorder(null);
        txt_hoten.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_hoten.setOpaque(false);
        jPanel1.add(txt_hoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 200, -1));

        txt_phongban.setBackground(new java.awt.Color(255, 204, 204));
        txt_phongban.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_phongban.setOpaque(false);
        jPanel1.add(txt_phongban, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 180, -1));

        txt_chucvu.setBackground(new java.awt.Color(255, 204, 204));
        txt_chucvu.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_chucvu.setOpaque(false);
        jPanel1.add(txt_chucvu, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 200, -1));

        txt_bacluong.setBackground(new java.awt.Color(255, 204, 204));
        txt_bacluong.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        txt_bacluong.setOpaque(false);
        jPanel1.add(txt_bacluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 200, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 180, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 200, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 170, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 200, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 170, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 170, -1));

        gioitinh_nu.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        gioitinh_nu.setForeground(new java.awt.Color(255, 255, 255));
        gioitinh_nu.setText("Nữ");
        gioitinh_nu.setOpaque(false);
        jPanel1.add(gioitinh_nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        gioitinh_nam.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        gioitinh_nam.setForeground(new java.awt.Color(255, 255, 255));
        gioitinh_nam.setText("Nam");
        gioitinh_nam.setOpaque(false);
        jPanel1.add(gioitinh_nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        jLabel15.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ngày Sinh:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        jDateChooser2.setBackground(new java.awt.Color(255, 255, 255, 0));
        jDateChooser2.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jDateChooser2.setOpaque(false);
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 160, -1));

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255, 0));
        jDateChooser1.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jDateChooser1.setOpaque(false);
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 180, -1));

        jLabel16.setFont(new java.awt.Font("UVN Van", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("THÊM NHÂN SỰ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 200, 40));

        jLabel1.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Họ tên:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quê quán:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Giới tính:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dân tộc:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Số điện thoại:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Trình độ:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Chuyên ngành:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phòng ban:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Đoàn thể:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mã nhân sự:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Chức vụ:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Bậc lương:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, -1, -1));

        jLabel13.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ngày tham gia:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, -1));

        jLabel14.setFont(new java.awt.Font("UVN Van", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Chính trị:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        txt_chinhtri.setColumns(20);
        txt_chinhtri.setRows(5);
        txt_chinhtri.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txt_chinhtri);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 200, 120));

        txt_doanthe.setColumns(20);
        txt_doanthe.setRows(5);
        txt_doanthe.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txt_doanthe);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 200, 150));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/detailInfor.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 820, 500));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        try{
                boolean isOK;
                byte[] person_image;
                if(imageChange){
                    File image = new File(filename);
                    FileInputStream fis = new FileInputStream(image);
                    ByteArrayOutputStream bos = new ByteArrayOutputStream();
                    byte[] buf = new byte[1024];
                    for(int readNum; (readNum=fis.read(buf))!=-1;){
                        bos.write(buf,0,readNum);
                }
                person_image=bos.toByteArray();
                }
                else
                {
                    person_image=null;
                }
                isOK = new NhanSu().addNS((Integer)txt_bacluong.getSelectedItem(),
                        ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText(),
                        txt_mans.getText(),
                        txt_hoten.getText(),
                        ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText(),
                        txt_quequan.getText(),
                        txt_dantoc.getText(),
                        txt_sdt.getText(),
                        txt_trinhdo.getText(),
                        txt_chuyennganh.getText(),
                        ((ComboItem)txt_phongban.getSelectedItem()).getValue(),
                        ((ComboItem)txt_chucvu.getSelectedItem()).getValue(),
                        txt_chinhtri.getText(),
                        txt_doanthe.getText(),
                        gioitinh_nam.isSelected()?true:false,
                        person_image);
                if (isOK)
                {
                    JOptionPane.showMessageDialog(this,"Thêm thành công!");
                    this.dispose();
                    previousPanel.LoadData();
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Thêm thất bại!");
                }
            }
            catch(Exception e){
                
            }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(this);
        File f = chooser.getSelectedFile();
        String filenamez = f.getAbsolutePath();
        if(filenamez!=null)
        {
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(filenamez).getImage().getScaledInstance(lb_avt.getWidth(), lb_avt.getHeight(), Image.SCALE_SMOOTH));
            lb_avt.setIcon(imageIcon);
            imageChange = true;
            filename = filenamez;
        }
    }//GEN-LAST:event_btn_save1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detailInforAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detailInforAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detailInforAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detailInforAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                detailInforAdd dialog = new detailInforAdd(new hosoPanel(new java.awt.Frame()), new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_save1;
    private javax.swing.JRadioButton gioitinh_nam;
    private javax.swing.JRadioButton gioitinh_nu;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lb_avt;
    private javax.swing.JComboBox<Integer> txt_bacluong;
    private javax.swing.JTextArea txt_chinhtri;
    private javax.swing.JComboBox<ComboItem> txt_chucvu;
    private javax.swing.JTextField txt_chuyennganh;
    private javax.swing.JTextField txt_dantoc;
    private javax.swing.JTextArea txt_doanthe;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_mans;
    private javax.swing.JComboBox<ComboItem> txt_phongban;
    private javax.swing.JTextField txt_quequan;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_trinhdo;
    // End of variables declaration//GEN-END:variables
}
